1st module Capstone
Sirvelasque/capstonePage pull request #1
Opened 2022-02-10 05:22 UTC by Sirvelasque

- Create 2 pages of the website About and home pages
- Headline seccion with custom background
- Responsive design
- Features section made with javascript
- Custom topic

#link to loom video
- https://www.loom.com/share/dcd10db783484b3395cbb1cac4e03c63

2022-02-10 06:38 UTC, micheaol requested changes
Hi @Sirvelasque , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-10 06:38 UTC, micheaol commented on html/about.html
> +    </footer>
Please ensure that the `About Page footer` has a dark background according to the requirement.

2022-02-10 06:38 UTC, micheaol commented on index.html
> +    </section>
Please ensure that the pages look almost identical to the original design.

Your Implementation | Figma Design
:---:|:---:
   
![your_design](https://user-images.githubusercontent.com/10332499/153350762-636e2713-e5d7-4014-be1e-05a43c5ec1ca.PNG) | ![design](https://user-images.githubusercontent.com/10332499/153350789-b65fb35c-78a8-445d-b02e-305b066e722d.PNG)

2022-02-11 17:55 UTC, Deepakdanger approved these changes
Hi @Sirvelasque, 

### Status: Approved ✔️

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-11 17:56 UTC, merged